# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='actor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61\x63tor.proto\"\x19\n\nsendStrMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x19\n\x08strReply\x12\r\n\x05reply\x18\x01 \x01(\t\"\x1a\n\x0bsendByteMsg\x12\x0b\n\x03msg\x18\x01 \x01(\x0c\"\x1a\n\tbyteReply\x12\r\n\x05reply\x18\x01 \x01(\x0c\x32\x37\n\x0bStrStrActor\x12(\n\x0csend_message\x12\x0b.sendStrMsg\x1a\t.strReply\"\x00\x32;\n\rByteByteActor\x12*\n\x0csend_message\x12\x0c.sendByteMsg\x1a\n.byteReply\"\x00\x62\x06proto3')
)




_SENDSTRMSG = _descriptor.Descriptor(
  name='sendStrMsg',
  full_name='sendStrMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='sendStrMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=40,
)


_STRREPLY = _descriptor.Descriptor(
  name='strReply',
  full_name='strReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='strReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=67,
)


_SENDBYTEMSG = _descriptor.Descriptor(
  name='sendByteMsg',
  full_name='sendByteMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='sendByteMsg.msg', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=95,
)


_BYTEREPLY = _descriptor.Descriptor(
  name='byteReply',
  full_name='byteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='byteReply.reply', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['sendStrMsg'] = _SENDSTRMSG
DESCRIPTOR.message_types_by_name['strReply'] = _STRREPLY
DESCRIPTOR.message_types_by_name['sendByteMsg'] = _SENDBYTEMSG
DESCRIPTOR.message_types_by_name['byteReply'] = _BYTEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sendStrMsg = _reflection.GeneratedProtocolMessageType('sendStrMsg', (_message.Message,), {
  'DESCRIPTOR' : _SENDSTRMSG,
  '__module__' : 'actor_pb2'
  # @@protoc_insertion_point(class_scope:sendStrMsg)
  })
_sym_db.RegisterMessage(sendStrMsg)

strReply = _reflection.GeneratedProtocolMessageType('strReply', (_message.Message,), {
  'DESCRIPTOR' : _STRREPLY,
  '__module__' : 'actor_pb2'
  # @@protoc_insertion_point(class_scope:strReply)
  })
_sym_db.RegisterMessage(strReply)

sendByteMsg = _reflection.GeneratedProtocolMessageType('sendByteMsg', (_message.Message,), {
  'DESCRIPTOR' : _SENDBYTEMSG,
  '__module__' : 'actor_pb2'
  # @@protoc_insertion_point(class_scope:sendByteMsg)
  })
_sym_db.RegisterMessage(sendByteMsg)

byteReply = _reflection.GeneratedProtocolMessageType('byteReply', (_message.Message,), {
  'DESCRIPTOR' : _BYTEREPLY,
  '__module__' : 'actor_pb2'
  # @@protoc_insertion_point(class_scope:byteReply)
  })
_sym_db.RegisterMessage(byteReply)



_STRSTRACTOR = _descriptor.ServiceDescriptor(
  name='StrStrActor',
  full_name='StrStrActor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=125,
  serialized_end=180,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_message',
    full_name='StrStrActor.send_message',
    index=0,
    containing_service=None,
    input_type=_SENDSTRMSG,
    output_type=_STRREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STRSTRACTOR)

DESCRIPTOR.services_by_name['StrStrActor'] = _STRSTRACTOR


_BYTEBYTEACTOR = _descriptor.ServiceDescriptor(
  name='ByteByteActor',
  full_name='ByteByteActor',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=182,
  serialized_end=241,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_message',
    full_name='ByteByteActor.send_message',
    index=0,
    containing_service=None,
    input_type=_SENDBYTEMSG,
    output_type=_BYTEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BYTEBYTEACTOR)

DESCRIPTOR.services_by_name['ByteByteActor'] = _BYTEBYTEACTOR

# @@protoc_insertion_point(module_scope)
